apiVersion: v1
description: Helm chart for Elasticsearch cluster deployment
name: elasticsearch-picnic
version: 8.0.0-SNAPSHOT
appVersion: 8.0.0-SNAPSHOT
sources:
  - https://github.com/elastic/elasticsearch